export { default as Cpu } from '/public/Image/cpu.svg'
export { default as Monitor } from '/public/Image/monitor.svg'
export { default as Motherboard } from '/public/Image/motherboard.svg'
export { default as PowerSupply } from '/public/Image/powsersupply.svg'
export { default as Ram } from '/public/Image/ram.svg'
export { default as Storage } from '/public/Image/storage.svg'